# Generated by Django 2.1.15 on 2022-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220607_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='category',
            new_name='tutorial_category',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='series',
            new_name='tutorial_series',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='category_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
